<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\deps\Structs\src\Structs.csproj" AdditionalProperties="UseDouble=false" />
    <ProjectReference Include="..\deps\Graphics\src\Graphics.csproj" AdditionalProperties="UseDouble=false" />
    <ProjectReference Include="..\deps\Windowing\src\Windowing.csproj" AdditionalProperties="UseDouble=false" />
    <ProjectReference Include="..\deps\GUI\src\GUI.csproj" AdditionalProperties="UseDouble=false" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  
  <!-- <ItemGroup>
    <None Update="Layouts/passwordInput.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Layouts/passwordManage.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup> -->

</Project>
