// 
// Code auto generated by GuiXml.
// 

using System;
using Zene.Structs;
using Zene.Graphics;
using Zene.Windowing;
using Zene.GUI;

namespace Encryption
{
    internal static class empty
    {
        internal static void LoadGUI(ElementList el)
        {
            IElement root = el.Source;
            
            Label label1 = new Label();
            label1.Layout = new TextLayout(5f, 5f, 0f, 0f, true);
            label1.BorderWidth = 0f;
            label1.TextSize = 20f;
            label1.Text = @"Drop file to load or Ctrl + A to create new.";
            el.Add(label1);
            
        }
    }
}