// 
// Code auto generated by GuiXml.
// 

using System;
using Zene.Structs;
using Zene.Graphics;
using Zene.Windowing;
using Zene.GUI;

namespace Encryption
{
    internal static class passwordInput
    {
        internal static void LoadGUI(ElementList el, Program program)
        {
            IElement root = el.Source;
            
            Label label1 = new Label();
            label1.Layout = new TextLayout(5f, 5f, 0f, 64f, false);
            label1.BorderWidth = 0f;
            label1.TextSize = 12f;
            label1.TextColour = ColourF.Grey;
            el.Add(label1);
            
            Container container1 = new Container();
            container1.Layout = new FixedLayout(0f, 0f, 200f, 100f);
            Label label2 = new Label();
            label2.Layout = new TextLayout(5f, 5f, 0f, 0.65f, true);
            label2.BorderWidth = 0f;
            label2.TextSize = 20f;
            label2.Text = @"Enter Password";
            container1.Children.Add(label2);
            
            PasswordEnter passwordenter1 = new PasswordEnter();
            passwordenter1.Layout = new TextLayout(7f, 2f, 0f, 0f, 1.8f, 0f, true);
            passwordenter1.TextSize = 15f;
            passwordenter1.BackgroundColour = new ColourF(0f, 0f, 0f);
            passwordenter1.PasswordEntered += program.OnPasswordEntered;
            container1.Children.Add(passwordenter1);
            
            container1.Colour = new ColourF(0.1f, 0.1f, 0.1f);
            el.Add(container1);
            
        }
    }
}