// 
// Code auto generated by GuiXml.
// 

using System;
using Zene.Structs;
using Zene.Graphics;
using Zene.Windowing;
using Zene.GUI;

namespace Encryption
{
    internal static class passwordManage
    {
        internal static void LoadGUI(ElementList el)
        {
            IElement root = el.Source;
            
            Container container1 = new Container();
            container1.Layout = new Layout(0f, 0f, 2f, 2f);
            container1.LayoutManager = new BlockLayout(5.0f);
            el.Add(container1);
        }
    }
}